version: '3.8'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: cip_postgres
    environment:
      POSTGRES_DB: cip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cip"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Applicazione Flask
  app:
    build: .
    container_name: cip_app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cip
      SECRET_KEY: dev-secret-key-change-in-production
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Redis per sessioni (opzionale)
  redis:
    image: redis:7-alpine
    container_name: cip_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
